main: br.com.eterniaserver.eterniartp.EterniaRTP

name: EterniaRTP
version: '${project.version}'
author: Yuri Nogueira
description: Simple RTP Plugin.
api-version: '1.13'
depend:
  - EterniaLib
  - Vault
softdepend:
  - EterniaServer