name: EterniaRTP
version: '${version}'
main: br.com.eterniaserver.eterniartp.EterniaRTP
dev-url: https://github.com/EterniaServer/EterniaRTP
api-version: 1.20
depend:
  - EterniaLib
softdepend:
  - Vault
author: Yuri Nogueira
description: Simple Random Teleport Plugin
website: www.eterniaserver.com.br
