main: br.com.eterniaserver.EterniaRTP

name: EterniaRTP
version: '${project.version}'
author: Yuri Nogueira
description: Simple RTP Plugin.
api-version: '1.13'
softdepend: [Vault]
commands:
  rtp:
    description: Teleporta aleatoriamente.
    aliases: [randomteleport]